### PR TITLE
Add Zuplo to API Gateway

### PR DESCRIPTION
**Pull request by AdrianMachado**
Add Zuplo to API gateway section

### CODE REVIEW

**Comment by AdrianMachado** [comment]
@wmariuss - do you think you'll get to reviewing my PR this week?

**Comment by wmariuss** [comment]
This product has also a open source version?

**Comment by AdrianMachado** [comment]
> This product has also a open source version?

Parts of the product are open source, like RateMyOpenAPI is our governance product, and we will be releasing our API developer portal OSS soon

**Comment by AdrianMachado** [comment]
@wmariuss - is having an open source version a requirement for the list?

**Comment by wmariuss** [comment]
No, just to play with it?

**Comment by wmariuss** [comment]
I recently reviewed your product and found it quite interesting. However, as a DevOps professional, I prefer using tools that are decoupled, meaning applications (in your case the gateway app) are separate from the API Gateway platform. In other words, I don't want my application management to be dependent on a single platform for both the app and API Gateway.
Also control is paramount in any DevOps environment. I believe that most DevOps engineers share this sentiment. Having the ability to manage and oversee all components of the development and deployment process is crucial for ensuring efficiency, security, and flexibility.

Thank you for the contribution.

**Pull request closed without merging**
